version: '3'

services:  
  # postgres database
  db:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=testpassword
      - POSTGRES_DB=postgres

  # django web server
  web:
    build: .
    image: django_webapp:latest
    container_name: cs5331_19_web
    command: bash -c "chmod +x ./wait-for-it.sh &&
      ./wait-for-it.sh db:5432 --
      python manage.py migrate && python manage.py runserver 0.0.0.0:8080"
    ports:
      - "8080:8080"
    depends_on:
      - db

  # front-end server
  nginx:
    image: nginx:latest
    container_name: cs5331_19_nginx
    ports:
      - "80:80"
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - ./frontendapp:/frontendapp
    depends_on:
      - web