# Generated by Django 2.0 on 2018-02-19 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='publish_date',
            field=models.DateTimeField(verbose_name='Publish Date'),
        ),
        migrations.AlterField(
            model_name='diary',
            name='text',
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='diary',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
